# Generated by Django 4.0.1 on 2022-02-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_desc', models.CharField(max_length=400)),
                ('item_price', models.IntegerField()),
                ('item_image', models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fpngtree.com%2Fso%2Ffood&psig=AOvVaw1km3_N2qf6peDbXyUiZinl&ust=1645335970666000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCOD8vaGIi_YCFQAAAAAdAAAAABAI', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_desc', models.CharField(max_length=400)),
                ('item_price', models.IntegerField()),
                ('item_image', models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fpngtree.com%2Fso%2Ffood&psig=AOvVaw1km3_N2qf6peDbXyUiZinl&ust=1645335970666000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCOD8vaGIi_YCFQAAAAAdAAAAABAI', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_desc', models.CharField(max_length=400)),
                ('item_price', models.IntegerField()),
                ('item_image', models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fpngtree.com%2Fso%2Ffood&psig=AOvVaw1km3_N2qf6peDbXyUiZinl&ust=1645335970666000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCOD8vaGIi_YCFQAAAAAdAAAAABAI', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
