# Generated by Django 4.0.3 on 2022-04-13 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
