# Generated by Django 4.0.1 on 2022-02-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_breakfast_dinner_lunch_delete_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fdribbble.com%2Fshots%2F4187820-404-Food-Not-Found&psig=AOvVaw11RK1iHlxif02JyUpc9XQV&ust=1645338723250000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCLj16MGSi_YCFQAAAAAdAAAAABAD', max_length=500),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fdribbble.com%2Fshots%2F4187820-404-Food-Not-Found&psig=AOvVaw11RK1iHlxif02JyUpc9XQV&ust=1645338723250000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCLj16MGSi_YCFQAAAAAdAAAAABAD', max_length=500),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fdribbble.com%2Fshots%2F4187820-404-Food-Not-Found&psig=AOvVaw11RK1iHlxif02JyUpc9XQV&ust=1645338723250000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCLj16MGSi_YCFQAAAAAdAAAAABAD', max_length=500),
        ),
    ]
